version: '3.8'

services:
  pricing-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./visualizations:/app/visualizations
      - ./logs:/app/logs
      - ./pricing_strategies:/app/pricing_strategies
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped 